events { worker_connections 1024; }

http {
    # QUAN TRỌNG: Phải có dòng này để trình duyệt hiểu file CSS, JS
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Định nghĩa các nhóm Backend
    upstream producer_backend {
        server api-producer:3000;
    }
    upstream consumer_backend {
        server consumer-service:3001;
    }

    server {
        listen 80;
        server_name nhanit.id.vn www.nhanit.id.vn;

        # 1. Phục vụ Frontend (VueJS)
        location / {
            root /usr/share/nginx/html; # Thư mục chứa code Vue sau khi build
            index index.html index.htm;
            # Fix lỗi F5 bị 404 trong Vue Router
            try_files $uri $uri/ /index.html;
        }

        # 2. Proxy cho Producer API
        location /api/producers/ {
            proxy_pass http://producer_backend/producers/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        # Proxy cho Admin API (nằm trong Producer)
        location /api/admin/ {
            proxy_pass http://producer_backend/admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Proxy cho Consumer API
        location /api/consumers/ {
            proxy_pass http://consumer_backend/consumers/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 4. Proxy cho WebSocket
        location /socket.io/ {
            proxy_pass http://producer_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}